version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: react-native-webview
      - dependency-name: "@babel/core"
        versions:
          - ">=7.x"
      - dependency-name: react-native-screens
        versions:
          - ">=3.x"
      - dependency-name: "@types/react"
        versions:
          - ">=17.x"
      - dependency-name: "react-native-web"
        versions:
          - ">=17.x"
      - dependency-name: "@types/react-native"
        versions:
          - ">=63.x"
      - dependency-name: "@types/react-test-renderer"
        versions:
          - ">=17.x"
      - dependency-name: "react-native-reanimated"
        versions:
          - ">=2.x"
