sudo: false
language: node_js
node_js:
  - "11"

before_install:
  # fix timezone to developers' timezone
  - export TZ=Europe/Berlin

install:
  - npm install

script:
  - npx tsc
  - npm test

after_success:
  - npm install codecov
  - npx codecov
