sudo: false
language: node_js
node_js:
  - "11"

before_install:
  # fix timezone to developers' timezone
  - export TZ=Europe/Berlin

# .travis.yml
install:
  - npm ci
# keep the npm cache around to speed up installs
cache:
  directories:
    - "~/.npm"

script:
  - npx tsc
  - npm test -- --ci

after_success:
  - npm install codecov
  - npx codecov
